### ISSUE TITLE
EyeWitness -f option

### ISSUE THREAD

**Issue by zer0-t** [skorov/rduserenum#1]
Hi skorov,

Found a bug in your script.

The -f option in EyeWitness must be -x for the nmap.xml import. Otherwise your script will end up giving errors.

python /opt/eyewitness-git/EyeWitness.py --rdp -f %s/nmap.xml -d %s/raw'

python /opt/eyewitness-git/EyeWitness.py --rdp -x %s/nmap.xml -d %s/raw'

**Comment by skorov** [comment]
Thanks! Seems like EW changed it's flag. So I've fixed the issue.

**Comment by zer0-t** [comment]
Great, thanks for the quick response!
