### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by Stepman123** [skorov/rduserenum#2]
Dedian 8.6 and Ubuntu 14.04

> ...
Nmap scan report for swarbrook.plus.com (192.229.0.254)
Host is up (0.000039s latency).
PORT     STATE    SERVICE
3389/tcp filtered ms-wbt-server

Nmap scan report for 192.229.0.255
Host is up (0.000052s latency).
PORT     STATE    SERVICE
3389/tcp filtered ms-wbt-server

Nmap done: 256 IP addresses (256 hosts up) scanned in 14.40 seconds
Getting screenshots from RDP...
python: can't open file '/opt/eyewitness-git/EyeWitness.py': [Errno 2] No such file or directory
()
Making images clearer for OCR...
Traceback (most recent call last):
  File "./rduserenum.py", line 29, in <module>
    for i in os.listdir('%s/raw/screens' % tmpDir):
OSError: [Errno 2] No such file or directory: '/tmp/rduserenum/raw/screens'
root@debian:~/Documents/1#

**Comment by skorov** [comment]
Hi there! Thanks for showing an interest. 

Judging from the log, seems like you don't have your EyeWitness script in the right place? It should be in '/opt/eyewitness-git/EyeWitness.py'.

Feel free to change this setting to point to your local EyeWitness script.

Cheers!

**Comment by skorov** [comment]
Hi @Stepman123, can you confirm that this fixed your issue so that I may close this Issue?

**Comment by Stepman123** [comment]
Hi skorov, yes, it helped.
