### ISSUE TITLE
IP List

### ISSUE THREAD

**Issue by ampf27** [skorov/rduserenum#3]
.

**Comment by ampf27** [comment]
I have closed this issue but in the meantime another issue occured so to not open a new issue I have reopened this one.

I have tried the program but after the scan I got a error message related with HTML module missing it happens that it is installed. Can you take a look on this?

https://www65.zippyshare.com/v/91DlQlDC/file.html
(the error message)


Thank you

**Comment by skorov** [comment]
Hey @ampf27. Sorry, but I've stopped supporting this repo. There are better tools out there now: E.g. https://github.com/sensepost/gowitness
